name    'jhoblitt-ganglia'
version '0.0.4'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/rayber/puppet-ganglia'
source 'https://github.com/rayber/puppet-ganglia.git'
summary 'install and configure the ganglia gmond & gmetad daemons + web front end'
description 'install and configure the ganglia gmond & gmetad daemons + web front end. Rewritten from https://github.com/jhoblitt/ganglia as we are using EL6 ganglia latest packages in El5'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
